module.exports = {
  banners: {
    code: 0,
    data: [
      {
        businessId: 0,
        dateAdd: "2024-06-27 12:52:21",
        dateUpdate: "2020-02-20 09:54:37",
        id: 339806,
        linkType: 0,
        paixu: 0,
        picUrl:
          "https://dcdn.it120.cc/2019/12/29/2e79921a-92b3-4d1d-8182-cb3d524be5fb.png",
        shopId: 0,
        status: 0,
        statusStr: "显示",
        title: "首页轮播图",
        type: "index",
        userId: 65263,
      },
      {
        businessId: 0,
        dateAdd: "2024-06-27 12:52:21",
        dateUpdate: "2020-02-20 09:54:31",
        id: 339805,
        linkType: 0,
        paixu: 0,
        picUrl:
          "https://dcdn.it120.cc/2019/12/29/daca65ee-4347-4792-a490-ccbac4b3c1d7.png",
        shopId: 0,
        status: 0,
        statusStr: "显示",
        title: "首页轮播图",
        type: "index",
        userId: 65263,
      },
      {
        businessId: 0,
        dateAdd: "2024-06-27 12:52:21",
        dateUpdate: "2020-02-20 09:54:27",
        id: 339804,
        linkType: 0,
        linkUrl: "",
        paixu: 0,
        picUrl:
          "https://dcdn.it120.cc/2019/12/29/8396f65d-d615-46d8-b2e5-aa41820b9fe5.png",
        shopId: 0,
        status: 0,
        statusStr: "显示",
        title: "首页轮播图",
        type: "index",
        userId: 65263,
      },
    ],
    msg: "success",
  },
  category: {
    code: 0,
    data: [
      {
        icon: "https://cdn.it120.cc/apifactory/2019/04/09/f89753a227d26a3fe9ccc6f975857bb6.png",
        id: 454847,
        isUse: true,
        key: "1",
        level: 1,
        name: "上装",
        paixu: 0,
        pid: 0,
        shopId: 0,
        type: "index",
        userId: 65263,
        wxsph:
          '{"id": null, "name": null, "first_cat_id": 6706, "third_cat_id": 6722, "qualification": "", "second_cat_id": 6714, "dialogFormVisible": null, "qualification_type": 0, "product_qualification": "《国家强制性产品认证证书》（CCC安全认证证书）或《强制性认证产品符合自我声明》、具有传真功能还需上传《电信设备进网许可证》", "product_qualification_type": 1}',
      },
      {
        icon: "https://cdn.it120.cc/apifactory/2019/04/09/5bfffd6ad0d4483870f024a3ed936528.png",
        id: 454848,
        isUse: true,
        key: "2",
        level: 1,
        name: "裤装",
        paixu: 0,
        pid: 0,
        shopId: 0,
        type: "",
        userId: 65263,
        wxsph:
          '{"id": null, "name": null, "audit_id": "RQAAAJtwENEBAA56hbATIA", "auditResult": {"status": 0}, "first_cat_id": 7419, "third_cat_id": 7421, "qualification": "1、国产商品需提供：申请主体的《食品经营许可证》或《食品生产许可证》或《预包装食品销售备案凭证》。 2、进口商品需提供：①申请主体的《食品经营许可证》或《预包装食品销售备案凭证》；②近一年内的《出入境检验检疫证明》或《出入境检验检疫卫生证书》；③供货协议或采购合同等材料。 （注：①若申请主体为办理出入境检验证的收货人，则无需提供供货协议或采购合同等材料；②自贸区企业若无法提供《食品经营许可证》，需要提供营业执照（经营范围需包含食品经营（预包装食品）））", "second_cat_id": 7420, "dialogFormVisible": null, "qualification_type": 1, "qualification_passed": true, "product_qualification": " （选填）1、若经营清真食品，需提供生产厂商的《清真食品生产经营许可证》或相关证件； 2、标记农产品产地的农产品，需提供《农产品地理标志登记证书》； 3、声称获得无公害农产品认证的农产品，需提供《无公害农产品认证证书》； 4、声称获得绿色食品认证的食品，需提供《绿色食品证书》； 5、声称获得有机食品认证的食品，需提供《有机产品认证证书》", "product_qualification_type": 2}',
      },
      {
        icon: "https://cdn.it120.cc/apifactory/2019/04/09/8d32c254e2cb86d2d42c99b768d136b6.png",
        id: 454849,
        isUse: true,
        key: "4",
        level: 1,
        name: "特价区",
        paixu: 0,
        pid: 0,
        shopId: 0,
        type: "",
        userId: 65263,
      },
      {
        icon: "https://cdn.it120.cc/apifactory/2019/04/09/d800327091f216e2c83db8af7b6be306.png",
        id: 454850,
        isUse: true,
        key: "5",
        level: 1,
        name: "裙装",
        paixu: 0,
        pid: 0,
        shopId: 0,
        type: "",
        userId: 65263,
      },
      {
        icon: "https://cdn.it120.cc/apifactory/2019/04/09/cfee29650d6ae58a4bb1f84a3d899450.png",
        id: 454851,
        isUse: true,
        key: "6",
        level: 1,
        name: "套装",
        paixu: 0,
        pid: 0,
        shopId: 0,
        type: "",
        userId: 65263,
      },
      {
        icon: "https://cdn.it120.cc/apifactory/2019/04/09/6b3136cda73c99453ac93a1c5a9deebf.png",
        id: 454852,
        isUse: true,
        key: "7",
        level: 1,
        name: "外套",
        paixu: 0,
        pid: 0,
        shopId: 0,
        type: "",
        userId: 65263,
        wxsph:
          '{"id": null, "name": null, "first_cat_id": 6033, "third_cat_id": 517004, "qualification": "", "second_cat_id": 6057, "dialogFormVisible": null, "qualification_type": 0, "product_qualification": "", "product_qualification_type": 0}',
      },
      {
        icon: "https://cdn.it120.cc/apifactory/2019/04/09/9a7356187fce687ce568ba7381685299.png",
        id: 454853,
        isUse: true,
        key: "8",
        level: 1,
        name: "秒杀",
        paixu: 0,
        pid: 0,
        shopId: 0,
        type: "",
        userId: 65263,
      },
      {
        icon: "https://cdn.it120.cc/apifactory/2019/04/09/7773b4c204280ba194514594f7070ac9.png",
        id: 454854,
        isUse: true,
        key: "9",
        level: 1,
        name: "内裤",
        paixu: 0,
        pid: 0,
        shopId: 0,
        type: "",
        userId: 65263,
      },
      {
        icon: "https://cdn.it120.cc/apifactory/2019/04/09/60f41bf042d201b48a7115d22344320f.png",
        id: 454855,
        isUse: true,
        key: "10",
        level: 1,
        name: "袜子",
        paixu: 0,
        pid: 0,
        shopId: 0,
        type: "",
        userId: 65263,
      },
      {
        icon: "https://cdn.it120.cc/apifactory/2019/04/09/cdb16ac9c66bc211b82bd947452526f4.png",
        id: 454856,
        isUse: true,
        key: "11",
        level: 1,
        name: "鞋",
        paixu: 0,
        pid: 0,
        shopId: 0,
        type: "",
        userId: 65263,
      },
    ],
    msg: "success",
  },
  goodsV2Category0: {
    code: 0,
    data: {
      result: [
        {
          afterSale: "0,1,2",
          barCode: "a0000000001",
          categoryId: 454847,
          characteristic: "兔毛，手感好，质量更好",
          commission: 0.0,
          commissionSettleType: 0,
          commissionType: 0,
          commissionUserType: 0,
          dateAdd: "2024-06-27 12:52:22",
          dateUpdate: "2024-06-25 14:44:38",
          fxType: 2,
          gotScore: 0,
          gotScoreType: 0,
          hasAddition: false,
          hasTourJourney: false,
          hidden: 0,
          id: 1829996,
          kanjia: false,
          kanjiaPrice: 0.0,
          limitation: false,
          logisticsId: 92115,
          maxCoupons: 1,
          miaosha: false,
          minBuyNumber: 1,
          minPrice: 189.0,
          minScore: 1,
          name: "兔毛马甲",
          numberFav: 0,
          numberGoodReputation: 0,
          numberOrders: 0,
          numberReputation: 0,
          numberSells: 0,
          originalPrice: 189.0,
          overseas: false,
          paixu: 0,
          persion: 0,
          pic: "https://cdn.it120.cc/apifactory/2019/06/25/76d3c433-96ea-4f41-b149-31ea0983cd8f.jpg",
          pingtuan: false,
          pingtuanPrice: 0.0,
          priceShopSell: 0.0,
          recommendStatus: 0,
          recommendStatusStr: "普通",
          seckillBuyNumber: 0,
          sellEnd: false,
          sellStart: true,
          shopId: 0,
          status: 0,
          statusStr: "上架",
          storeAlert: false,
          storeAlertNum: 9,
          stores: 0,
          stores0Unsale: true,
          storesExt1: 0,
          storesExt2: 0,
          subName: "bieming",
          type: 0,
          unit: "份",
          unusefulNumber: 0,
          usefulNumber: 0,
          userId: 65263,
          vetStatus: 1,
          views: 0,
          weight: 0.0,
        },
        {
          afterSale: "0,1,2",
          categoryId: 454847,
          characteristic: "男童风衣",
          commission: 0.0,
          commissionSettleType: 0,
          commissionType: 0,
          commissionUserType: 0,
          dateAdd: "2024-06-27 12:52:22",
          dateUpdate: "2024-06-24 10:53:59",
          fxType: 2,
          gotScore: 0,
          gotScoreType: 0,
          hasAddition: false,
          hasTourJourney: false,
          hidden: 0,
          id: 1829995,
          kanjia: false,
          kanjiaPrice: 0.0,
          limitation: false,
          logisticsId: 0,
          maxCoupons: 1,
          miaosha: false,
          minBuyNumber: 1,
          minPrice: 179.0,
          minScore: 0,
          name: "风衣",
          numberFav: 0,
          numberGoodReputation: 0,
          numberOrders: 0,
          numberReputation: 0,
          numberSells: 0,
          originalPrice: 189.0,
          overseas: false,
          paixu: 0,
          persion: 0,
          pic: "https://cdn.it120.cc/apifactory/2019/06/25/a0edbee6-44c2-453f-9398-01edfb355323.jpg",
          pingtuan: false,
          pingtuanPrice: 0.0,
          recommendStatus: 0,
          recommendStatusStr: "普通",
          seckillBuyNumber: 0,
          sellEnd: false,
          sellStart: true,
          shopId: 0,
          status: 0,
          statusStr: "上架",
          storeAlert: false,
          stores: 0,
          stores0Unsale: false,
          storesExt1: 0,
          storesExt2: 0,
          type: 0,
          unit: "份",
          unusefulNumber: 0,
          usefulNumber: 0,
          userId: 65263,
          vetStatus: 1,
          views: 0,
          weight: 0.0,
        },
        {
          afterSale: "0,1,2",
          categoryId: 454847,
          characteristic: "貂绒毛衣，男孩女孩都适合",
          commission: 0.0,
          commissionSettleType: 0,
          commissionType: 0,
          commissionUserType: 0,
          dateAdd: "2024-06-27 12:52:22",
          dateStart: "2017-09-22 14:41:04",
          dateUpdate: "2024-06-25 14:11:40",
          discountPrice: 0.0,
          fxType: 2,
          gotScore: 0,
          gotScoreType: 0,
          hasAddition: false,
          hasTourJourney: false,
          hidden: 0,
          id: 1829994,
          kanjia: false,
          kanjiaPrice: 0.0,
          limitation: false,
          logisticsId: 92115,
          maxCoupons: 1,
          miaosha: false,
          minBuyNumber: 1,
          minPrice: 139.0,
          minScore: 0,
          name: "貂绒毛衣",
          numberFav: 0,
          numberGoodReputation: 0,
          numberOrders: 0,
          numberReputation: 0,
          numberSells: 0,
          originalPrice: 189.0,
          overseas: false,
          paixu: 0,
          persion: 0,
          pic: "https://cdn.it120.cc/apifactory/2019/06/25/344b8ae0-fb32-4752-bbec-7218ba887a17.jpg",
          pingtuan: false,
          pingtuanPrice: 0.0,
          priceShopSell: 0.0,
          recommendStatus: 0,
          recommendStatusStr: "普通",
          seckillBuyNumber: 0,
          sellEnd: false,
          sellStart: true,
          shopId: 0,
          status: 0,
          statusStr: "上架",
          storeAlert: false,
          stores: 36,
          stores0Unsale: false,
          storesExt1: 0,
          storesExt2: 0,
          subName: "我想养一头牛 牛 哈哈哈",
          type: 0,
          unit: "份",
          unusefulNumber: 0,
          usefulNumber: 0,
          userId: 65263,
          vetStatus: 1,
          views: 0,
          weight: 0.0,
        },
        {
          afterSale: "0,1,2",
          categoryId: 454847,
          characteristic: "高品质的夹克外套",
          commission: 0.0,
          commissionSettleType: 0,
          commissionType: 0,
          commissionUserType: 0,
          dateAdd: "2024-06-27 12:52:22",
          dateStart: "2017-09-22 15:33:20",
          dateUpdate: "2024-06-26 07:52:51",
          fxType: 2,
          gotScore: 0,
          gotScoreType: 0,
          hasAddition: false,
          hasTourJourney: false,
          hidden: 0,
          id: 1829993,
          kanjia: false,
          kanjiaPrice: 0.0,
          limitation: false,
          logisticsId: 92115,
          maxCoupons: 1,
          miaosha: false,
          minBuyNumber: 1,
          minPrice: 159.0,
          minScore: 0,
          name: "夹克外套",
          numberFav: 0,
          numberGoodReputation: 0,
          numberOrders: 0,
          numberReputation: 0,
          numberSells: 0,
          originalPrice: 189.0,
          overseas: false,
          paixu: 0,
          persion: 0,
          pic: "https://cdn.it120.cc/apifactory/2019/06/25/455e2434-ad8b-4bab-a4d7-724427b16228.gif",
          pingtuan: false,
          pingtuanPrice: 0.0,
          recommendStatus: 0,
          recommendStatusStr: "普通",
          seckillBuyNumber: 0,
          sellEnd: false,
          sellStart: true,
          shopId: 0,
          status: 0,
          statusStr: "上架",
          storeAlert: false,
          stores: 36,
          stores0Unsale: false,
          storesExt1: 0,
          storesExt2: 0,
          type: 0,
          unusefulNumber: 0,
          usefulNumber: 0,
          userId: 65263,
          vetStatus: 1,
          views: 0,
          weight: 0.0,
        },
        {
          afterSale: "0,1,2",
          categoryId: 454847,
          characteristic: "加绒毛衣，不久的北方就要穿到了",
          commission: 0.0,
          commissionSettleType: 0,
          commissionType: 0,
          commissionUserType: 0,
          dateAdd: "2024-06-27 12:52:22",
          dateStart: "2017-09-22 15:42:40",
          dateUpdate: "2024-06-19 11:16:50",
          fxType: 2,
          gotScore: 0,
          gotScoreType: 0,
          hasAddition: false,
          hasTourJourney: false,
          hidden: 0,
          id: 1829992,
          kanjia: false,
          kanjiaPrice: 0.0,
          limitation: false,
          logisticsId: 92115,
          maxCoupons: 1,
          miaosha: false,
          minBuyNumber: 1,
          minPrice: 59.0,
          minScore: 0,
          name: "加绒毛衣",
          numberFav: 0,
          numberGoodReputation: 0,
          numberOrders: 0,
          numberReputation: 0,
          numberSells: 0,
          originalPrice: 89.0,
          overseas: false,
          paixu: 0,
          persion: 0,
          pic: "https://cdn.it120.cc/apifactory/2019/06/26/69dd39f1-f7ad-49fd-8211-c9c7a3003c4a.jpg",
          pingtuan: false,
          pingtuanPrice: 0.0,
          recommendStatus: 0,
          recommendStatusStr: "普通",
          seckillBuyNumber: 0,
          sellEnd: false,
          sellStart: true,
          shopId: 0,
          status: 0,
          statusStr: "上架",
          storeAlert: false,
          stores: 56,
          stores0Unsale: false,
          storesExt1: 0,
          storesExt2: 0,
          type: 0,
          unusefulNumber: 0,
          usefulNumber: 0,
          userId: 65263,
          vetStatus: 1,
          views: 0,
          weight: 0.0,
        },
        {
          afterSale: "0,1,2",
          categoryId: 454847,
          characteristic: "加绒毛衣，纯棉加绒款",
          commission: 0.0,
          commissionSettleType: 0,
          commissionType: 0,
          commissionUserType: 0,
          dateAdd: "2024-06-27 12:52:22",
          dateStart: "2017-09-22 15:54:02",
          dateUpdate: "2024-06-26 15:20:24",
          fxType: 2,
          gotScore: 0,
          gotScoreType: 0,
          hasAddition: false,
          hasTourJourney: false,
          hidden: 0,
          id: 1829991,
          kanjia: false,
          kanjiaPrice: 0.0,
          limitation: false,
          logisticsId: 92115,
          maxCoupons: 1,
          miaosha: false,
          minBuyNumber: 1,
          minPrice: 59.0,
          minScore: 0,
          name: "加绒毛衣",
          numberFav: 0,
          numberGoodReputation: 0,
          numberOrders: 0,
          numberReputation: 0,
          numberSells: 0,
          originalPrice: 89.0,
          overseas: false,
          paixu: 0,
          persion: 0,
          pic: "https://cdn.it120.cc/apifactory/2019/06/26/9ea289ce-9ce7-4a2a-9342-25ae4abfd3f3.jpg",
          pingtuan: false,
          pingtuanPrice: 0.0,
          recommendStatus: 0,
          recommendStatusStr: "普通",
          seckillBuyNumber: 0,
          sellEnd: false,
          sellStart: true,
          shopId: 0,
          status: 0,
          statusStr: "上架",
          storeAlert: false,
          stores: 56,
          stores0Unsale: false,
          storesExt1: 0,
          storesExt2: 0,
          type: 0,
          unusefulNumber: 0,
          usefulNumber: 0,
          userId: 65263,
          vetStatus: 1,
          views: 0,
          weight: 0.0,
        },
        {
          afterSale: "0,1,2",
          categoryId: 454847,
          characteristic: "加绒毛衣，中大童",
          commission: 0.0,
          commissionSettleType: 0,
          commissionType: 0,
          commissionUserType: 0,
          dateAdd: "2024-06-27 12:52:22",
          dateStart: "2017-09-22 16:00:25",
          dateUpdate: "2024-06-18 00:38:57",
          fxType: 2,
          gotScore: 0,
          gotScoreType: 0,
          hasAddition: false,
          hasTourJourney: false,
          hidden: 0,
          id: 1829990,
          kanjia: false,
          kanjiaPrice: 0.0,
          limitation: false,
          logisticsId: 92115,
          maxCoupons: 1,
          miaosha: false,
          minBuyNumber: 1,
          minPrice: 59.0,
          minScore: 0,
          name: "加绒毛衣",
          numberFav: 0,
          numberGoodReputation: 0,
          numberOrders: 0,
          numberReputation: 0,
          numberSells: 0,
          originalPrice: 89.0,
          overseas: false,
          paixu: 0,
          persion: 0,
          pic: "https://cdn.it120.cc/apifactory/2019/06/26/5d19bb9b-4727-4fd3-9ab8-170ffde12bdc.jpg",
          pingtuan: false,
          pingtuanPrice: 0.0,
          recommendStatus: 0,
          recommendStatusStr: "普通",
          seckillBuyNumber: 0,
          sellEnd: false,
          sellStart: true,
          shopId: 0,
          status: 0,
          statusStr: "上架",
          storeAlert: false,
          stores: 56,
          stores0Unsale: false,
          storesExt1: 0,
          storesExt2: 0,
          type: 0,
          unusefulNumber: 0,
          usefulNumber: 0,
          userId: 65263,
          vetStatus: 1,
          views: 0,
          weight: 0.0,
        },
        {
          afterSale: "0,1,2",
          categoryId: 454847,
          characteristic: "加绒毛衣，性价比高",
          commission: 0.0,
          commissionSettleType: 0,
          commissionType: 0,
          commissionUserType: 0,
          dateAdd: "2024-06-27 12:52:22",
          dateStart: "2017-09-22 16:06:03",
          dateUpdate: "2024-06-26 07:52:51",
          fxType: 2,
          gotScore: 0,
          gotScoreType: 0,
          hasAddition: false,
          hasTourJourney: false,
          hidden: 0,
          id: 1829989,
          kanjia: false,
          kanjiaPrice: 0.0,
          limitation: false,
          logisticsId: 92115,
          maxCoupons: 1,
          miaosha: false,
          minBuyNumber: 1,
          minPrice: 59.0,
          minScore: 0,
          name: "加绒毛衣",
          numberFav: 0,
          numberGoodReputation: 0,
          numberOrders: 0,
          numberReputation: 0,
          numberSells: 0,
          originalPrice: 89.0,
          overseas: false,
          paixu: 0,
          persion: 0,
          pic: "https://cdn.it120.cc/apifactory/2019/06/26/338e1ef3-c455-4873-ae9d-66ef22536251.jpg",
          pingtuan: false,
          pingtuanPrice: 0.0,
          recommendStatus: 0,
          recommendStatusStr: "普通",
          seckillBuyNumber: 0,
          sellEnd: false,
          sellStart: true,
          shopId: 0,
          status: 0,
          statusStr: "上架",
          storeAlert: false,
          stores: 56,
          stores0Unsale: false,
          storesExt1: 0,
          storesExt2: 0,
          type: 0,
          unusefulNumber: 0,
          usefulNumber: 0,
          userId: 65263,
          vetStatus: 1,
          views: 0,
          weight: 0.0,
        },
        {
          afterSale: "0,1,2",
          categoryId: 454847,
          characteristic: "女孩子喜欢的圈圈毛衣，加绒",
          commission: 0.0,
          commissionSettleType: 0,
          commissionType: 0,
          commissionUserType: 0,
          dateAdd: "2024-06-27 12:52:22",
          dateStart: "2017-09-24 08:35:52",
          dateUpdate: "2024-06-24 13:32:55",
          fxType: 2,
          gotScore: 0,
          gotScoreType: 0,
          hasAddition: false,
          hasTourJourney: false,
          hidden: 0,
          id: 1829988,
          kanjia: false,
          kanjiaPrice: 0.0,
          limitation: false,
          logisticsId: 92115,
          maxCoupons: 1,
          miaosha: false,
          minBuyNumber: 1,
          minPrice: 59.0,
          minScore: 0,
          name: "毛衣",
          numberFav: 0,
          numberGoodReputation: 0,
          numberOrders: 0,
          numberReputation: 0,
          numberSells: 0,
          originalPrice: 89.0,
          overseas: false,
          paixu: 0,
          persion: 0,
          pic: "https://cdn.it120.cc/apifactory/2019/06/26/aa3633df-62f2-4ff2-8773-ec546b4eabe4.jpg",
          pingtuan: false,
          pingtuanPrice: 0.0,
          recommendStatus: 0,
          recommendStatusStr: "普通",
          seckillBuyNumber: 0,
          sellEnd: false,
          sellStart: true,
          shopId: 0,
          status: 0,
          statusStr: "上架",
          storeAlert: false,
          stores: 56,
          stores0Unsale: false,
          storesExt1: 0,
          storesExt2: 0,
          type: 0,
          unusefulNumber: 0,
          usefulNumber: 0,
          userId: 65263,
          vetStatus: 1,
          views: 0,
          weight: 0.0,
        },
        {
          afterSale: "0,1,2",
          categoryId: 454847,
          characteristic: "可爱毛衣",
          commission: 0.0,
          commissionSettleType: 0,
          commissionType: 0,
          commissionUserType: 0,
          dateAdd: "2024-06-27 12:52:22",
          dateStart: "2017-09-24 08:48:14",
          dateUpdate: "2024-06-18 00:37:58",
          fxType: 2,
          gotScore: 0,
          gotScoreType: 0,
          hasAddition: false,
          hasTourJourney: false,
          hidden: 0,
          id: 1829987,
          kanjia: false,
          kanjiaPrice: 0.0,
          limitation: false,
          logisticsId: 3958,
          maxCoupons: 1,
          miaosha: false,
          minBuyNumber: 1,
          minPrice: 59.0,
          minScore: 0,
          name: "毛衣",
          numberFav: 0,
          numberGoodReputation: 0,
          numberOrders: 0,
          numberReputation: 0,
          numberSells: 0,
          originalPrice: 89.0,
          overseas: false,
          paixu: 0,
          persion: 0,
          pic: "https://cdn.it120.cc/apifactory/2019/06/26/64b2cbba-b3cd-4d9c-87e7-4fce4ffe3ec6.jpg",
          pingtuan: false,
          pingtuanPrice: 0.0,
          recommendStatus: 0,
          recommendStatusStr: "普通",
          seckillBuyNumber: 0,
          sellEnd: false,
          sellStart: true,
          shopId: 0,
          status: 0,
          statusStr: "上架",
          storeAlert: false,
          stores: 105,
          stores0Unsale: false,
          storesExt1: 0,
          storesExt2: 0,
          type: 0,
          unusefulNumber: 0,
          usefulNumber: 0,
          userId: 65263,
          vetStatus: 1,
          views: 0,
          weight: 0.0,
        },
        {
          afterSale: "0,1,2",
          categoryId: 454847,
          characteristic: "多色可选的马甲",
          commission: 0.0,
          commissionSettleType: 0,
          commissionType: 0,
          commissionUserType: 0,
          dateAdd: "2024-06-27 12:52:22",
          dateStart: "2017-09-24 08:55:13",
          dateUpdate: "2024-06-20 15:29:58",
          fxType: 2,
          gotScore: 0,
          gotScoreType: 0,
          hasAddition: false,
          hasTourJourney: false,
          hidden: 0,
          id: 1829986,
          kanjia: false,
          kanjiaPrice: 0.0,
          limitation: false,
          logisticsId: 92115,
          maxCoupons: 1,
          miaosha: false,
          minBuyNumber: 1,
          minPrice: 49.0,
          minScore: 0,
          name: "马甲",
          numberFav: 0,
          numberGoodReputation: 0,
          numberOrders: 0,
          numberReputation: 0,
          numberSells: 0,
          originalPrice: 89.0,
          overseas: false,
          paixu: 0,
          persion: 0,
          pic: "https://cdn.it120.cc/apifactory/2019/06/26/2071d45b-a68a-4852-a8de-df58955f1fdc.jpg",
          pingtuan: false,
          pingtuanPrice: 0.0,
          recommendStatus: 0,
          recommendStatusStr: "普通",
          seckillBuyNumber: 0,
          sellEnd: false,
          sellStart: true,
          shopId: 0,
          status: 0,
          statusStr: "上架",
          storeAlert: false,
          stores: 105,
          stores0Unsale: false,
          storesExt1: 0,
          storesExt2: 0,
          type: 0,
          unusefulNumber: 0,
          usefulNumber: 0,
          userId: 65263,
          vetStatus: 1,
          views: 0,
          weight: 0.0,
        },
        {
          afterSale: "0,1,2",
          categoryId: 454847,
          characteristic: "小童爆款马甲，这个天气刚刚好穿",
          commission: 0.0,
          commissionSettleType: 0,
          commissionType: 0,
          commissionUserType: 0,
          dateAdd: "2024-06-27 12:52:22",
          dateStart: "2017-09-24 09:14:00",
          dateUpdate: "2024-06-26 11:48:15",
          fxType: 2,
          gotScore: 0,
          gotScoreType: 0,
          hasAddition: false,
          hasTourJourney: false,
          hidden: 0,
          id: 1829985,
          kanjia: false,
          kanjiaPrice: 0.0,
          limitation: false,
          logisticsId: 92115,
          maxCoupons: 1,
          miaosha: false,
          minBuyNumber: 1,
          minPrice: 49.0,
          minScore: 0,
          name: "爆款背心",
          numberFav: 0,
          numberGoodReputation: 0,
          numberOrders: 0,
          numberReputation: 0,
          numberSells: 0,
          originalPrice: 89.0,
          overseas: false,
          paixu: 0,
          persion: 0,
          pic: "https://cdn.it120.cc/apifactory/2019/06/26/cabd5e5b-3ec3-48a9-9035-57098f878f2e.jpg",
          pingtuan: false,
          pingtuanPrice: 0.0,
          recommendStatus: 0,
          recommendStatusStr: "普通",
          seckillBuyNumber: 0,
          sellEnd: false,
          sellStart: true,
          shopId: 0,
          status: 0,
          statusStr: "上架",
          storeAlert: false,
          stores: 105,
          stores0Unsale: false,
          storesExt1: 0,
          storesExt2: 0,
          type: 0,
          unusefulNumber: 0,
          usefulNumber: 0,
          userId: 65263,
          vetStatus: 1,
          views: 0,
          weight: 0.0,
        },
        {
          afterSale: "0,1,2",
          categoryId: 454847,
          characteristic: "小童毛衣背心",
          commission: 0.0,
          commissionSettleType: 0,
          commissionType: 0,
          commissionUserType: 0,
          dateAdd: "2024-06-27 12:52:22",
          dateStart: "2017-09-24 09:24:49",
          dateUpdate: "2024-06-24 14:21:39",
          fxType: 2,
          gotScore: 0,
          gotScoreType: 0,
          hasAddition: false,
          hasTourJourney: false,
          hidden: 0,
          id: 1829984,
          kanjia: false,
          kanjiaPrice: 0.0,
          limitation: false,
          logisticsId: 92115,
          maxCoupons: 1,
          miaosha: false,
          minBuyNumber: 1,
          minPrice: 49.0,
          minScore: 0,
          name: "毛衣背心",
          numberFav: 0,
          numberGoodReputation: 0,
          numberOrders: 0,
          numberReputation: 0,
          numberSells: 0,
          originalPrice: 89.0,
          overseas: false,
          paixu: 0,
          persion: 0,
          pic: "https://cdn.it120.cc/apifactory/2019/06/26/430932d8-e60b-42ef-988f-ac15e0d69df8.jpg",
          pingtuan: false,
          pingtuanPrice: 0.0,
          recommendStatus: 0,
          recommendStatusStr: "普通",
          seckillBuyNumber: 0,
          sellEnd: false,
          sellStart: true,
          shopId: 0,
          status: 0,
          statusStr: "上架",
          storeAlert: false,
          stores: 106,
          stores0Unsale: false,
          storesExt1: 0,
          storesExt2: 0,
          type: 0,
          unusefulNumber: 0,
          usefulNumber: 0,
          userId: 65263,
          vetStatus: 1,
          views: 0,
          weight: 0.0,
        },
        {
          afterSale: "0,1,2",
          categoryId: 454847,
          characteristic: "小狗图案毛衣",
          commission: 0.0,
          commissionSettleType: 0,
          commissionType: 0,
          commissionUserType: 0,
          dateAdd: "2024-06-27 12:52:22",
          dateStart: "2017-09-24 09:33:38",
          dateUpdate: "2024-06-27 09:30:12",
          fxType: 2,
          gotScore: 0,
          gotScoreType: 0,
          hasAddition: false,
          hasTourJourney: false,
          hidden: 0,
          id: 1829983,
          kanjia: false,
          kanjiaPrice: 0.0,
          limitation: false,
          logisticsId: 92115,
          maxCoupons: 1,
          miaosha: false,
          minBuyNumber: 1,
          minPrice: 49.0,
          minScore: 0,
          name: "小狗图案毛衣",
          numberFav: 0,
          numberGoodReputation: 0,
          numberOrders: 0,
          numberReputation: 0,
          numberSells: 0,
          originalPrice: 89.0,
          overseas: false,
          paixu: 0,
          persion: 0,
          pic: "https://cdn.it120.cc/apifactory/2019/06/26/a613fd66-62ce-4c26-b5f4-0573b068f5b4.jpg",
          pingtuan: false,
          pingtuanPrice: 0.0,
          priceShopSell: 0.0,
          recommendStatus: 0,
          recommendStatusStr: "普通",
          seckillBuyNumber: 0,
          sellEnd: false,
          sellStart: true,
          shopId: 0,
          status: 0,
          statusStr: "上架",
          storeAlert: false,
          stores: 105,
          stores0Unsale: false,
          storesExt1: 0,
          storesExt2: 0,
          type: 0,
          unit: "份",
          unusefulNumber: 0,
          usefulNumber: 0,
          userId: 65263,
          vetStatus: 1,
          views: 0,
          weight: 0.0,
        },
        {
          afterSale: "0,1,2",
          categoryId: 454847,
          characteristic: "中小童毛衣",
          commission: 0.0,
          commissionSettleType: 0,
          commissionType: 0,
          commissionUserType: 0,
          dateAdd: "2024-06-27 12:52:22",
          dateStart: "2017-09-24 09:43:08",
          dateUpdate: "2024-06-26 11:06:03",
          fxType: 2,
          gotScore: 0,
          gotScoreType: 0,
          hasAddition: false,
          hasTourJourney: false,
          hidden: 0,
          id: 1829982,
          kanjia: false,
          kanjiaPrice: 0.0,
          limitation: false,
          logisticsId: 92115,
          maxCoupons: 1,
          miaosha: false,
          minBuyNumber: 1,
          minPrice: 49.0,
          minScore: 0,
          name: "毛衣",
          numberFav: 0,
          numberGoodReputation: 0,
          numberOrders: 0,
          numberReputation: 0,
          numberSells: 0,
          originalPrice: 89.0,
          overseas: false,
          paixu: 0,
          persion: 0,
          pic: "https://cdn.it120.cc/apifactory/2019/06/26/1e3564a6-6646-40e7-9476-1281f4041245.jpg",
          pingtuan: false,
          pingtuanPrice: 0.0,
          recommendStatus: 0,
          recommendStatusStr: "普通",
          seckillBuyNumber: 0,
          sellEnd: false,
          sellStart: true,
          shopId: 0,
          status: 0,
          statusStr: "上架",
          storeAlert: false,
          stores: 105,
          stores0Unsale: false,
          storesExt1: 0,
          storesExt2: 0,
          type: 0,
          unusefulNumber: 0,
          usefulNumber: 0,
          userId: 65263,
          vetStatus: 1,
          views: 0,
          weight: 0.0,
        },
        {
          afterSale: "0,1,2",
          categoryId: 454855,
          characteristic: "可爱打底袜",
          commission: 0.0,
          commissionSettleType: 0,
          commissionType: 0,
          commissionUserType: 0,
          dateAdd: "2024-06-27 12:52:22",
          dateStart: "2017-09-25 09:10:58",
          dateUpdate: "2024-06-26 07:48:41",
          fxType: 2,
          gotScore: 0,
          gotScoreType: 0,
          hasAddition: false,
          hasTourJourney: false,
          hidden: 0,
          id: 1829981,
          kanjia: false,
          kanjiaPrice: 0.0,
          limitation: false,
          logisticsId: 459,
          maxCoupons: 1,
          miaosha: false,
          minBuyNumber: 1,
          minPrice: 12.0,
          minScore: 0,
          name: "可爱打底袜",
          numberFav: 0,
          numberGoodReputation: 0,
          numberOrders: 0,
          numberReputation: 0,
          numberSells: 0,
          originalPrice: 25.0,
          overseas: false,
          paixu: 0,
          persion: 0,
          pic: "https://cdn.it120.cc/apifactory/2019/06/26/2573dac9-e6eb-4f03-8577-acbf7a8cf96c.jpg",
          pingtuan: false,
          pingtuanPrice: 0.0,
          recommendStatus: 0,
          recommendStatusStr: "普通",
          seckillBuyNumber: 0,
          sellEnd: false,
          sellStart: true,
          shopId: 0,
          status: 0,
          statusStr: "上架",
          storeAlert: false,
          stores: 105,
          stores0Unsale: false,
          storesExt1: 0,
          storesExt2: 0,
          type: 0,
          unusefulNumber: 0,
          usefulNumber: 0,
          userId: 65263,
          vetStatus: 1,
          views: 0,
          weight: 0.0,
        },
        {
          afterSale: "0,1,2",
          categoryId: 454855,
          characteristic:
            "可开档的小童打底袜，中童尺码也有，小童6个月到24个月，中童4岁到8岁",
          commission: 0.0,
          commissionSettleType: 0,
          commissionType: 0,
          commissionUserType: 0,
          dateAdd: "2024-06-27 12:52:22",
          dateStart: "2017-09-25 09:15:10",
          dateUpdate: "2024-06-27 10:15:22",
          fxType: 2,
          gotScore: 0,
          gotScoreType: 0,
          hasAddition: false,
          hasTourJourney: false,
          hidden: 0,
          id: 1829980,
          kanjia: false,
          kanjiaPrice: 0.0,
          limitation: false,
          logisticsId: 459,
          maxCoupons: 1,
          miaosha: false,
          minBuyNumber: 1,
          minPrice: 20.0,
          minScore: 0,
          name: "打底袜",
          numberFav: 0,
          numberGoodReputation: 0,
          numberOrders: 0,
          numberReputation: 0,
          numberSells: 0,
          originalPrice: 30.0,
          overseas: false,
          paixu: 0,
          persion: 0,
          pic: "https://cdn.it120.cc/apifactory/2019/06/26/74880087-c883-49f9-afe7-d5117283e61e.jpg",
          pingtuan: false,
          pingtuanPrice: 0.0,
          recommendStatus: 0,
          recommendStatusStr: "普通",
          seckillBuyNumber: 0,
          sellEnd: false,
          sellStart: true,
          shopId: 0,
          status: 0,
          statusStr: "上架",
          storeAlert: false,
          stores: 105,
          stores0Unsale: false,
          storesExt1: 0,
          storesExt2: 0,
          type: 0,
          unusefulNumber: 0,
          usefulNumber: 0,
          userId: 65263,
          vetStatus: 1,
          views: 0,
          weight: 0.0,
        },
        {
          afterSale: "0,1,2",
          categoryId: 454855,
          characteristic: "拼色打底袜",
          commission: 0.0,
          commissionSettleType: 0,
          commissionType: 0,
          commissionUserType: 0,
          dateAdd: "2024-06-27 12:52:22",
          dateStart: "2017-09-25 09:22:26",
          dateUpdate: "2024-06-24 23:18:17",
          fxType: 2,
          gotScore: 0,
          gotScoreType: 0,
          hasAddition: false,
          hasTourJourney: false,
          hidden: 0,
          id: 1829979,
          kanjia: false,
          kanjiaPrice: 0.0,
          limitation: false,
          logisticsId: 459,
          maxCoupons: 1,
          miaosha: false,
          minBuyNumber: 1,
          minPrice: 12.0,
          minScore: 0,
          name: "可爱拼色打底袜",
          numberFav: 0,
          numberGoodReputation: 0,
          numberOrders: 0,
          numberReputation: 0,
          numberSells: 0,
          originalPrice: 25.0,
          overseas: false,
          paixu: 0,
          persion: 0,
          pic: "https://cdn.it120.cc/apifactory/2019/06/26/38f2fd1c-1f2a-466c-b09a-185dcf98db75.jpg",
          pingtuan: false,
          pingtuanPrice: 0.0,
          recommendStatus: 0,
          recommendStatusStr: "普通",
          seckillBuyNumber: 0,
          sellEnd: false,
          sellStart: true,
          shopId: 0,
          status: 0,
          statusStr: "上架",
          storeAlert: false,
          stores: 104,
          stores0Unsale: false,
          storesExt1: 0,
          storesExt2: 0,
          type: 0,
          unusefulNumber: 0,
          usefulNumber: 0,
          userId: 65263,
          vetStatus: 1,
          views: 0,
          weight: 0.0,
        },
        {
          afterSale: "0,1,2",
          barCode: "",
          categoryId: 454856,
          characteristic: "保暖雨鞋",
          commission: 5.0,
          commissionSettleType: 0,
          commissionType: 2,
          commissionUserType: 0,
          dateAdd: "2024-06-27 12:52:22",
          dateStart: "2017-10-18 00:00:00",
          dateUpdate: "2024-06-27 10:15:23",
          fxType: 2,
          gotScore: 11,
          gotScoreType: 0,
          hasAddition: false,
          hasTourJourney: false,
          hidden: 0,
          id: 1829978,
          kanjia: false,
          kanjiaPrice: 0.0,
          limitation: false,
          logisticsId: 92115,
          maxCoupons: 1,
          miaosha: false,
          minBuyNumber: 1,
          minPrice: 48.0,
          minScore: 3,
          name: "雨鞋",
          numberFav: 0,
          numberGoodReputation: 0,
          numberOrders: 0,
          numberReputation: 0,
          numberSells: 0,
          originalPrice: 58.0,
          overseas: false,
          paixu: 0,
          persion: 0,
          pic: "https://cdn.it120.cc/apifactory/2019/07/05/748d7ea6-9aa0-4783-9f5d-3c05d4b3e166.gif",
          pingtuan: false,
          pingtuanPrice: 0.0,
          recommendStatus: 0,
          recommendStatusStr: "普通",
          seckillBuyNumber: 0,
          sellEnd: false,
          sellStart: true,
          shopId: 0,
          status: 0,
          statusStr: "上架",
          storeAlert: false,
          stores: 9999997,
          stores0Unsale: false,
          storesExt1: 0,
          storesExt2: 0,
          type: 0,
          unusefulNumber: 0,
          usefulNumber: 0,
          userId: 65263,
          vetStatus: 1,
          videoId: "",
          views: 0,
          weight: 0.0,
        },
        {
          afterSale: "0,1,2",
          barCode: "",
          categoryId: 454847,
          characteristic: "尼多熊袜子，适合秋冬天",
          commission: 5.0,
          commissionSettleType: 0,
          commissionType: 2,
          commissionUserType: 0,
          dateAdd: "2024-06-27 12:52:22",
          dateUpdate: "2024-06-27 10:06:09",
          fxType: 2,
          gotScore: 0,
          gotScoreType: 0,
          hasAddition: false,
          hasTourJourney: false,
          hidden: 0,
          id: 1829977,
          kanjia: false,
          kanjiaPrice: 0.0,
          limitation: false,
          logisticsId: 92115,
          maxCoupons: 1,
          miaosha: false,
          minBuyNumber: 1,
          minPrice: 236.0,
          minScore: 0,
          name: "幼儿园园服韩版男女童装春秋季班服英伦学院风白色衬衫小学生校服",
          numberFav: 0,
          numberGoodReputation: 0,
          numberOrders: 0,
          numberReputation: 0,
          numberSells: 0,
          originalPrice: 500.0,
          overseas: false,
          paixu: 0,
          persion: 0,
          pic: "https://cdn.it120.cc/apifactory/2019/07/11/e9fb59ae-7e66-427d-8d47-642c3b733a0b.jpg",
          pingtuan: false,
          pingtuanPrice: 0.0,
          recommendStatus: 0,
          recommendStatusStr: "普通",
          seckillBuyNumber: 0,
          sellEnd: false,
          sellStart: true,
          shopId: 0,
          status: 0,
          statusStr: "上架",
          storeAlert: false,
          stores: 6,
          stores0Unsale: false,
          storesExt1: 0,
          storesExt2: 0,
          type: 0,
          unusefulNumber: 0,
          usefulNumber: 0,
          userId: 65263,
          vetStatus: 1,
          views: 0,
          weight: 0.0,
        },
      ],
      totalPage: 2,
      totalRow: 31,
    },
    msg: "success",
  },
  cmsCategory: {
    code: 0,
    data: [
      {
        id: 166719,
        isUse: true,
        level: 1,
        name: "常见问题",
        paixu: 0,
        pid: 0,
        shopId: 0,
        type: "qa",
        userId: 65263,
      },
      {
        id: 166720,
        isUse: true,
        level: 1,
        name: "购物指南",
        paixu: 0,
        pid: 0,
        shopId: 0,
        type: "qa",
        userId: 65263,
      },
      {
        id: 166721,
        isUse: true,
        level: 1,
        name: "订单指南",
        paixu: 0,
        pid: 0,
        shopId: 0,
        type: "qa",
        userId: 65263,
      },
      {
        id: 166722,
        isUse: true,
        level: 1,
        name: "支付问题",
        paixu: 0,
        pid: 0,
        shopId: 0,
        type: "qa",
        userId: 65263,
      },
      {
        id: 166723,
        isUse: true,
        level: 1,
        name: "物流问题",
        paixu: 0,
        pid: 0,
        shopId: 0,
        type: "qa",
        userId: 65263,
      },
      {
        id: 166724,
        isUse: true,
        level: 1,
        name: "售后问题",
        paixu: 0,
        pid: 0,
        shopId: 0,
        type: "qa",
        userId: 65263,
      },
      {
        id: 166725,
        isUse: true,
        level: 1,
        name: "退货细则",
        paixu: 0,
        pid: 0,
        shopId: 0,
        type: "qa",
        userId: 65263,
      },
      {
        id: 166726,
        isUse: true,
        level: 1,
        name: "协议规则",
        paixu: 0,
        pid: 0,
        shopId: 0,
        type: "qa",
        userId: 65263,
      },
      {
        id: 166727,
        isUse: true,
        level: 1,
        name: "招商加盟",
        paixu: 0,
        pid: 0,
        shopId: 0,
        type: "qa",
        userId: 65263,
      },
    ],
    msg: "success",
  },
  noticeList: {
    code: 0,
    data: {
      dataList: [
        {
          dateAdd: "2024-06-27 12:52:21",
          dateUpdate: "2023-08-19 09:32:57",
          descript:
            "新店开张，福利多多，多买多送，感谢支持 如需制作小程序，请联系我：",
          id: 45453,
          isRemind: false,
          isShow: true,
          remindUid: 0,
          title: "新店开张优惠多多，如需做小程序请联系我",
          userId: 65263,
        },
      ],
      totalPage: 1,
      totalRow: 1,
    },
    msg: "success",
  },
  goodsV2Recommend: {
    code: 0,
    data: {
      result: [
        {
          afterSale: "0,1,2",
          brandId: 3,
          categoryId: 454849,
          commission: 0.0,
          commissionSettleType: 0,
          commissionType: 0,
          commissionUserType: 0,
          dateAdd: "2024-06-27 12:52:22",
          dateUpdate: "2024-06-29 13:20:48",
          fxType: 2,
          gotScore: 0,
          gotScoreType: 0,
          hasAddition: true,
          hasTourJourney: false,
          hidden: 0,
          id: 1829971,
          kanjia: false,
          kanjiaPrice: 0.0,
          limitation: false,
          logisticsId: 92115,
          maxCoupons: 1,
          miaosha: false,
          minBuyNumber: 1,
          minPrice: 499.0,
          minScore: 0,
          name: "WiFi云标签机 FP-N20W",
          numberFav: 0,
          numberGoodReputation: 0,
          numberOrders: 0,
          numberReputation: 0,
          numberSells: 0,
          originalPrice: 0.0,
          overseas: true,
          paixu: 0,
          persion: 0,
          pic: "https://dcdn.it120.cc/2020/05/22/83618213-99b6-42ce-a672-becf466aa515.png",
          pingtuan: false,
          pingtuanPrice: 0.0,
          recommendStatus: 1,
          recommendStatusStr: "推荐",
          seckillBuyNumber: 0,
          sellEnd: false,
          sellStart: true,
          shopId: 0,
          status: 0,
          statusStr: "上架",
          storeAlert: false,
          stores: 9982,
          stores0Unsale: false,
          storesExt1: 0,
          storesExt2: 0,
          type: 0,
          unit: "份",
          unusefulNumber: 0,
          usefulNumber: 0,
          userId: 65263,
          vetStatus: 1,
          views: 1,
          weight: 0.0,
        },
        {
          afterSale: "0,1,2",
          categoryId: 454847,
          commission: 0.0,
          commissionSettleType: 0,
          commissionType: 0,
          commissionUserType: 0,
          dateAdd: "2024-06-27 12:52:22",
          dateUpdate: "2024-06-27 11:16:11",
          discountPrice: 0.0,
          fxType: 2,
          gotScore: 0,
          gotScoreType: 0,
          hasAddition: true,
          hasTourJourney: false,
          hidden: 0,
          id: 1829970,
          kanjia: false,
          kanjiaPrice: 0.0,
          limitation: false,
          logisticsId: 92115,
          maxCoupons: 1,
          miaosha: false,
          minBuyNumber: 1,
          minPrice: 299.0,
          minScore: 0,
          name: "小票打印机工厂定制版",
          numberFav: 0,
          numberGoodReputation: 0,
          numberOrders: 0,
          numberReputation: 0,
          numberSells: 0,
          originalPrice: 0.0,
          overseas: false,
          paixu: 0,
          persion: 0,
          pic: "https://dcdn.it120.cc/2020/04/15/0a86e7ef-3680-4f9f-a22c-2afb26672b7d.png",
          pingtuan: false,
          pingtuanPrice: 0.0,
          priceShopSell: 0.0,
          propertyIds: ",214454,214453,214452,",
          recommendStatus: 1,
          recommendStatusStr: "推荐",
          seckillBuyNumber: 0,
          sellEnd: false,
          sellStart: true,
          shopId: 0,
          status: 0,
          statusStr: "上架",
          storeAlert: false,
          stores: 4999903,
          stores0Unsale: false,
          storesExt1: 0,
          storesExt2: 0,
          tags: "",
          tax: 0.0,
          type: 0,
          unit: "台",
          unusefulNumber: 0,
          usefulNumber: 0,
          userId: 65263,
          vetStatus: 1,
          views: 0,
          weight: 0.0,
        },
        {
          afterSale: "0,1,2",
          categoryId: 454849,
          commission: 0.0,
          commissionSettleType: 0,
          commissionType: 0,
          commissionUserType: 0,
          dateAdd: "2024-06-27 12:52:22",
          dateUpdate: "2024-06-26 17:36:36",
          discountPrice: 0.0,
          fxType: 2,
          gotScore: 0,
          gotScoreType: 0,
          hasAddition: false,
          hasTourJourney: false,
          hidden: 0,
          id: 1829969,
          kanjia: false,
          kanjiaPrice: 0.0,
          limitation: false,
          logisticsId: 92115,
          maxCoupons: 0,
          miaosha: false,
          minBuyNumber: 1,
          minPrice: 99.0,
          minScore: 0,
          name: "扫码支付盒子扫码枪条码二维码扫描平台超市收银小白盒医保电子凭证支付宝微信收款扫码墩收钱机扫描神器",
          numberFav: 0,
          numberGoodReputation: 0,
          numberOrders: 0,
          numberReputation: 0,
          numberSells: 0,
          originalPrice: 0.0,
          overseas: false,
          paixu: 0,
          persion: 0,
          pic: "https://dcdn.it120.cc/2023/02/10/56aed798-e49d-432e-9417-7fdaf2d24e33.jpg",
          pingtuan: false,
          pingtuanPrice: 0.0,
          priceShopSell: 0.0,
          recommendStatus: 1,
          recommendStatusStr: "推荐",
          seckillBuyNumber: 0,
          sellEnd: false,
          sellStart: true,
          shopId: 0,
          status: 0,
          statusStr: "上架",
          storeAlert: false,
          stores: 9999997,
          stores0Unsale: false,
          storesExt1: 0,
          storesExt2: 0,
          tax: 0.0,
          type: 0,
          unit: "台",
          unusefulNumber: 0,
          usefulNumber: 0,
          userId: 65263,
          vetStatus: 1,
          views: 0,
          weight: 0.0,
        },
        {
          afterSale: "0,1,2",
          categoryId: 454849,
          commission: 0.0,
          commissionSettleType: 0,
          commissionType: 0,
          commissionUserType: 0,
          dateAdd: "2024-06-27 12:52:22",
          dateEndPingtuan: "2024-02-29 00:00:00",
          dateUpdate: "2024-06-26 19:52:17",
          discountPrice: 0.0,
          fxType: 2,
          gotScore: 0,
          gotScoreType: 0,
          hasAddition: false,
          hasTourJourney: false,
          hidden: 0,
          id: 1829965,
          iotControl: false,
          kanjia: false,
          kanjiaPrice: 0.0,
          limitation: false,
          logisticsId: 92115,
          maxCoupons: 1,
          miaosha: false,
          minBuyNumber: 1,
          minPrice: 49.0,
          minScore: 0,
          name: "ESP8266-esp01s-1路继电器 WIFI 智能插座/开关模块",
          numberFav: 0,
          numberGoodReputation: 0,
          numberOrders: 0,
          numberReputation: 0,
          numberSells: 0,
          originalPrice: 0.0,
          overseas: false,
          paixu: 0,
          persion: 0,
          pic: "https://dcdn.it120.cc/2023/09/16/5891b54c-9358-4b1f-91f5-a59268587187.jpg",
          pingtuan: false,
          pingtuanPrice: 0.0,
          priceShopSell: 0.0,
          recommendStatus: 1,
          recommendStatusStr: "推荐",
          seckillBuyNumber: 0,
          sellEnd: false,
          sellStart: true,
          shopId: 0,
          status: 0,
          statusStr: "上架",
          storeAlert: false,
          stores: 999996,
          stores0Unsale: false,
          storesExt1: 0,
          storesExt2: 0,
          tax: 0.0,
          type: 0,
          unit: "份",
          unusefulNumber: 0,
          usefulNumber: 0,
          userId: 65263,
          vetStatus: 1,
          views: 0,
          weight: 0.0,
        },
        {
          afterSale: "0,1,2",
          categoryId: 454849,
          commission: 0.0,
          commissionSettleType: 0,
          commissionType: 0,
          commissionUserType: 0,
          dateAdd: "2024-06-27 12:52:22",
          dateUpdate: "2024-06-27 11:31:40",
          discountPrice: 0.0,
          fxType: 2,
          gotScore: 0,
          gotScoreType: 0,
          hasAddition: false,
          hasTourJourney: false,
          hidden: 0,
          id: 1829964,
          iotControl: false,
          kanjia: false,
          kanjiaPrice: 0.0,
          limitation: false,
          logisticsId: 92114,
          maxCoupons: 1,
          miaosha: false,
          minBuyNumber: 1,
          minPrice: 99.0,
          minScore: 0,
          name: "ESP8266-esp12f-4路继电器 WIFI 智能插座/开关模块",
          numberFav: 0,
          numberGoodReputation: 0,
          numberOrders: 0,
          numberReputation: 0,
          numberSells: 0,
          originalPrice: 0.0,
          overseas: false,
          paixu: 0,
          persion: 0,
          pic: "https://dcdn.it120.cc/2023/09/16/c785b75e-2f34-42ee-9861-659eced2140c.png",
          pingtuan: false,
          pingtuanPrice: 0.0,
          priceShopSell: 0.0,
          recommendStatus: 1,
          recommendStatusStr: "推荐",
          seckillBuyNumber: 0,
          sellEnd: false,
          sellStart: true,
          shopId: 0,
          status: 0,
          statusStr: "上架",
          storeAlert: false,
          stores: 999997,
          stores0Unsale: false,
          storesExt1: 0,
          storesExt2: 0,
          tax: 0.0,
          type: 0,
          unit: "份",
          unusefulNumber: 0,
          usefulNumber: 0,
          userId: 65263,
          vetStatus: 1,
          views: 0,
          weight: 0.0,
        },
        {
          afterSale: "0,1,2",
          categoryId: 454849,
          commission: 0.0,
          commissionSettleType: 0,
          commissionType: 0,
          commissionUserType: 0,
          dateAdd: "2024-06-27 12:52:22",
          dateUpdate: "2024-06-27 11:12:06",
          discountPrice: 0.0,
          fxType: 2,
          gotScore: 0,
          gotScoreType: 0,
          hasAddition: true,
          hasTourJourney: false,
          hidden: 0,
          id: 1829963,
          iotControl: false,
          kanjia: false,
          kanjiaPrice: 0.0,
          limitation: false,
          logisticsId: 92114,
          maxCoupons: 1,
          miaosha: false,
          minBuyNumber: 1,
          minPrice: 300.0,
          minScore: 0,
          name: "ESP8266-esp12f-24路继电器 WIFI 智能插座/开关模块",
          numberFav: 0,
          numberGoodReputation: 0,
          numberOrders: 0,
          numberReputation: 0,
          numberSells: 0,
          originalPrice: 0.0,
          overseas: false,
          paixu: 0,
          persion: 0,
          pic: "https://dcdn.it120.cc/2023/10/15/d2296ee4-a450-4c9f-93c0-fc0655cc3f1d.jpg",
          pingtuan: false,
          pingtuanPrice: 0.0,
          priceShopSell: 0.0,
          recommendStatus: 1,
          recommendStatusStr: "推荐",
          seckillBuyNumber: 0,
          sellEnd: false,
          sellStart: true,
          shopId: 0,
          status: 0,
          statusStr: "上架",
          storeAlert: false,
          stores: 999997,
          stores0Unsale: false,
          storesExt1: 0,
          storesExt2: 0,
          tax: 0.0,
          type: 0,
          unit: "份",
          unusefulNumber: 0,
          usefulNumber: 0,
          userId: 65263,
          vetStatus: 1,
          views: 0,
          weight: 0.0,
        },
      ],
      totalPage: 1,
      totalRow: 6,
    },
    msg: "success",
  },
  goodsDynamic: {
    code: 0,
    data: [
      {
        nick: '用户abc',
        goodsName: '商品名称abc',
      },
      {
        nick: '用户123',
        goodsName: '商品名称123',
      }
    ]
  }
};
